---
title: "R Notebook"
output: html_notebook
---


```{r}
library(arrow)
library(tidyverse)
```


```{r}
ma_village_list_unique=read_parquet("ma_village_list_unique.parquet")
```


```{r}
ma_village_list_unique %>% filter(is_AB==1 & ct_yn==0 & outgrowth_yn==0)%>%
  group_by(state_name,cat_pop_sc)%>%
  count()%>% spread(key = "cat_pop_sc", value=n)%>%write_df_to_gsheet_oauth(sheet_url = "1YljQRjF-CEUw4yvod-oFnl2cpqfH_MKMRwz-uQpHLMs",sheet_name = "SC Population-State wise number")

ma_village_list_unique %>% filter(is_AB==1 & ct_yn==0 & outgrowth_yn==0)%>%
  group_by(district_name)%>%
  count()
```


```{r}
village_block_mapping=ma_village_list %>% group_by(state_code,district_code,block_code,block_name,village_code)%>% count()%>% filter(!is.na(village_code))

village_gp_mapping=ma_village_list %>% group_by(state_code,district_code,block_code,block_name,gp_code,gp_name,village_code)%>% count()%>% filter(!is.na(village_code))
```


```{r}

```



```{r}
ma_village_list_unique %>% filter(district_name=="ARARIA")%>%merge(village_block_mapping%>%select(3,4,5), by = "village_code",all.x = TRUE)%>% group_by(block_name)%>% summarise(total_population=sum(TOT_P),total_sc_pop=sum(P_SC),max_sc=max(P_SC),min_sc=(min(P_SC)))

ma_village_list_unique %>% filter(district_name=="ARARIA")%>%merge(village_gp_mapping%>%select(3:7), by = "village_code",all.x = TRUE)%>% group_by(block_code,gp_code)%>% summarise(total_population=sum(TOT_P),total_sc_pop=sum(P_SC),max_sc=max(P_SC),min_sc=(min(P_SC)))%>% filter(block_code==1631)
```

